Salesforce/SalesForceAssignment2/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/SalesForceAssignment2/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Student  Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/Training Assignment3/src/classes/TestClassTrigger.cls
/**
 * Name: TestDeleteNotallowedForFemaleStudent
 * Author: Anurag
 * Since: 2 February,2015
 * Description: Test the trigger not allowing to delete class if female student > 1
 */
@isTest
public class TestClassTrigger {
	/**
	 * Name:TestForDeleteClassNotAllowed_FemaleStudentGt1
	 * Description: Test the Trigger for female student greater than one
	 * Param:
	 * return:
	 */
	public static testMethod void  TestForDeleteClassNotAllowed_FemaleStudentGt1(){   
		
		// Creating a new object of class
		class__c cls = new class__c(Name__c = 'secondary',MaxSize__c=5,MyCount__c=0);
		// inserting cls
		insert cls;
		
		// Creating new Student 
		student__c newStudent1=new student__c(LastName__C ='xyz',Class__c = cls.id,Sex__c = 'Female'); 
		student__c newStudent2=new student__c(LastName__C ='abc',Class__c = cls.id,Sex__c = 'Female'); 
		
		// Inserting the student
		insert newStudent1;
		insert newStudent2;
		
		Test.startTest();
		try{
			delete cls;
		}
		catch(Exception e){ 
			system.debug('error in  line'+e.getLineNumber()+'due to'+e.getMessage());
		}
		Test.stopTest();



	}
}