Salesforce/SalesForceAssignment2/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/SalesForceAssignment2/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Student  Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/Salesforce Assignment/src/classes/GenerateMap.cls
public class GenerateMap 
{
	 public static Map<Class__c,Set<ID>>MapofClassAndStudentId()
        {
         list<Class__c>classList=[Select c.ID From Class__c c];
        Map<Class__c, Set<ID>> mapStudentInClass = new Map<Class__c, Set<ID>>();
        for(Integer i =0;i<classList.size();i++){
           Set<ID> studentSet= new Map<Id, Student__c>([Select s.ID from Student__c s where s.Class__r.id=:classList.get(i).Id ]).keySet();

           mapStudentInClass.put(classList[i],studentSet); 
        }
         System.debug(mapStudentInClass);
        return mapStudentInClass;

    }
}