Salesforce/SalesForceAssignment2/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/SalesForceAssignment2/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Student  Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/Training Assignment2/src/classes/DeleteStudentController.cls
/*
* Name:DeleteStudentController
* Author:anurag
* Since: 29 Januray,2015
*/ 
public class DeleteStudentController {
	// List of Selected Student for delete
    public  List<Student__c> selectedstd{get;set;}
    private ApexPages.StandardSetController standardController;
    
    public DeleteStudentController(ApexPages.StandardSetController standardController)
    {
        this.standardController = standardController;
    }
    
    public void getSelectedStudents()
    {       
        selectedstd = (List<Student__c>) standardController.getSelected();
        selectedstd =[select name,id,class__r.Name from student__c where id In : selectedstd];
    }
    public PageReference deleteStudent() {
        delete selectedstd ;
        System.debug('executed');
        return standardController.cancel();
    }
    
    
}